#!/bin/sh
# remember NIXUSER_PROFILE before cleaning environment
USE_GENTOO="$EBROOTGENTOO"
USE_GENTOO_VERSION="$EBVERSIONGENTOO"
USE_NIX="$NIXUSER_PROFILE"
# clean environment incl. user variables
module --force purge
unset CPATH
unset LIBRARY_PATH
unset LD_LIBRARY_PATH
export PATH=/usr/bin
EASYBUILD_ROOT=/cvmfs/soft.computecanada.ca/easybuild
if [ -z "$USE_NIX" ]; then
	module load gentoo/$USE_GENTOO_VERSION
	YEAR=$USE_GENTOO_VERSION
	export EASYBUILD_ALLOW_LOADED_MODULES=gentoo
	export LOCAL_EASYBUILD_CONFIGFILES=$EASYBUILD_ROOT/config.cfg,$EASYBUILD_ROOT/config-gentoo.cfg
else
	module load nixpkgs/16.09
	YEAR=2017
	unset USE_GENTOO
	unset USE_GENTOO_VERSION
	export LOCAL_EASYBUILD_CONFIGFILES=$EASYBUILD_ROOT/config.cfg,$EASYBUILD_ROOT/config-nix.cfg
	# use Gentoo Python 3.7.7 even here, only for EasyBuild itself
	export EB_PYTHON=/cvmfs/soft.computecanada.ca/gentoo/2020/usr/bin/python
fi
export EASYBUILD_SUBDIR_MODULES=modules/$YEAR
export EASYBUILD_SUBDIR_SOFTWARE=software/$YEAR
export EASYBUILD_SUBDIR_USER_MODULES=.local/easybuild/$EASYBUILD_SUBDIR_MODULES
export PATH=${PATH%%:/usr/bin}
module use $EASYBUILD_ROOT/$EASYBUILD_SUBDIR_MODULES
export EASYBUILD_ROBOT_PATHS=$EASYBUILD_ROOT/ebfiles_repo/$YEAR
export EASYBUILD_REPOSITORY='GitRepository'
if [ "$RSNT_ARCH" == avx2 ]; then
	export EASYBUILD_REPOSITORYPATH=$EASYBUILD_ROOT/ebfiles_repo.git,$YEAR
else
	export EASYBUILD_REPOSITORYPATH=$EASYBUILD_ROOT/ebfiles_repo_$RSNT_ARCH.git,$YEAR
	export EASYBUILD_ROBOT_PATHS=$EASYBUILD_ROOT/ebfiles_repo_$RSNT_ARCH/$YEAR:$EASYBUILD_ROBOT_PATHS
	export EASYBUILD_USE_CCACHE=''
fi

if [ "$RSNT_ARCH" == avx2 ]; then
	if [ -n "$USE_GENTOO" ]; then
	    export EASYBUILD_OPTARCH='NVHPC:tp=haswell;Intel:march=core-avx2 -axCore-AVX512;GCC:march=core-avx2'
	else
	    export EASYBUILD_OPTARCH='PGI:tp=haswell;Intel:xCore-AVX2;GCC:march=core-avx2'
	fi
elif [ "$RSNT_ARCH" == avx512 ]; then
	if [ -n "$USE_GENTOO" ]; then
	    export EASYBUILD_OPTARCH='NVHPC:tp=skylake;Intel:xCore-AVX512;GCC:march=skylake-avx512'
	else
	    export EASYBUILD_OPTARCH='PGI:tp=skylake;Intel:xCore-AVX512;GCC:march=skylake-avx512'
	fi
elif [ "$RSNT_ARCH" == avx ]; then
	if [ -n "$USE_GENTOO" ]; then
	    export EASYBUILD_OPTARCH='NVHPC:tp=sandybridge;Intel:xAVX;GCC:march=corei7-avx'
	else
	    export EASYBUILD_OPTARCH='PGI:tp=sandybridge;Intel:xAVX;GCC:march=corei7-avx'
	fi
elif [ "$RSNT_ARCH" == sse3 ]; then
	if [ -n "$USE_GENTOO" ]; then
	    export EASYBUILD_OPTARCH='NVHPC:tp=px;Intel:msse3;GCC:march=nocona -mtune=generic'
	else
	    export EASYBUILD_OPTARCH='PGI:tp=px;Intel:msse3;GCC:march=nocona -mtune=generic'
	fi
else
	echo please set RSNT_ARCH to sse3, avx, or avx2
	exit
fi
if [ -z $USE_GENTOO ]; then
    export EASYBUILD_OPTARCH="$EASYBUILD_OPTARCH;GCCcore:GENERIC"
fi

CURRENT_USER="$(whoami)"
if [ "$CURRENT_USER" != "ebuser" ] ; then
	export EASYBUILD_PREFIX=$HOME/.local/easybuild
	export EASYBUILD_SUBDIR_USER_MODULES=''
        export EASYBUILD_REPOSITORY='FileRepository'
	export EASYBUILD_REPOSITORYPATH=$EASYBUILD_PREFIX/ebfiles_repo,$YEAR
	export EASYBUILD_ROBOT_PATHS=$EASYBUILD_PREFIX/ebfiles_repo/$YEAR:$EASYBUILD_ROBOT_PATHS
	if [ "$RSNT_ARCH" != avx2 ]; then
	    export EASYBUILD_ROBOT_PATHS=$EASYBUILD_PREFIX/ebfiles_repo_$RSNT_ARCH/$YEAR:$EASYBUILD_ROBOT_PATHS
	fi
elif [ "$(id -ng)" != "ebuser" ] ; then
	# using ebuser with different group ID
	export EASYBUILD_INSTALLPATH_SOFTWARE=/cvmfs/restricted.computecanada.ca/easybuild/$EASYBUILD_SUBDIR_SOFTWARE
	export EASYBUILD_SOURCEPATH=/cvmfs/restricted.computecanada.ca/easybuild/sources
fi
export EASYBUILD_ROBOT_PATHS=$EASYBUILD_ROOT/easyconfigs:$EASYBUILD_ROBOT_PATHS
if [[ -n "$USE_GENTOO" ]]; then
	export EASYBUILD_HOOKS=$EASYBUILD_ROOT/cc_hooks_gentoo.py
else
	export EASYBUILD_HOOKS=$EASYBUILD_ROOT/cc_hooks_nix.py
fi
export EASYBUILD_BUILDPATH=$EASYBUILD_BUILDPATH/$RSNT_ARCH
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
if [ ! -d /cvmfs/local ]; then
	export EASYBUILD_USE_CCACHE=''
fi
export PYTHONPATH=$EASYBUILD_ROOT:$EASYBUILD_ROOT/site-packages
export RSNT_EASYBUILD_MAGIC_COOKIE=263ca73bb634185aab1d1b41627fdbba

# argument validation
for argument in "$@"; do
	if [[ "$CURRENT_USER" == "ebuser" ]]; then
		if [[ $argument =~ --inject-checksums* || $argument =~ --robot* || "$argument" == "-r" ]]; then
			echo "Please do not use $argument as $CURRENT_USER"
			exit 1
		fi
		if [[ $argument =~ .*.eb$ ]]; then
			if [[ $argument =~ ^/cvmfs/soft.computecanada.ca/easybuild/software/.* ]]; then
				# accept this path, it is used by the auto recompilation
				continue 
			elif [[ $argument =~ .*/.* ]]; then
				echo "Please do not use a path to specify the easyconfig."
				echo "Error on argument: $argument"
				exit 1
			fi
		fi
	fi
done

exec $EASYBUILD_ROOT/framework/eb --configfiles=$LOCAL_EASYBUILD_CONFIGFILES ${1+"$@"}
