#!/bin/bash
set -e
# remember NIXUSER_PROFILE before cleaning environment
USE_GENTOO="$EBROOTGENTOO"
USE_GENTOO_VERSION="$EBVERSIONGENTOO"
USE_NIX="$NIXUSER_PROFILE"
# clean environment incl. user variables
module --force purge
# use smaller arch-specific directory to avoid large spider cache rebuilds
export MODULEPATH=/cvmfs/soft.computecanada.ca/custom/modules-$RSNT_ARCH
if [[ ! -d $MODULEPATH ]]; then
	echo please set RSNT_ARCH to sse3, avx, avx2, or avx512
	exit 1
fi
unset CPATH
unset LIBRARY_PATH
unset LD_LIBRARY_PATH
export PATH=/usr/bin
if [[ $HOSTNAME =~ archimedes.c3.ca$ ]]; then
	export PATH=$PATH:/opt/software/slurm/bin
	export EASYBUILD_JOB_BACKEND='Slurm'
	export SBATCH_MEM_PER_CPU='1975m'
	export EASYBUILD_TMP_LOGDIR="/shared_tmp/logs"
fi
EASYBUILD_ROOT=/cvmfs/soft.computecanada.ca/easybuild
if [ -z "$USE_NIX" ]; then
	module load gentoo/$USE_GENTOO_VERSION
	YEAR=$USE_GENTOO_VERSION
	export EASYBUILD_ALLOW_LOADED_MODULES=gentoo
else
	module load nixpkgs/16.09
	YEAR=2017
	unset USE_GENTOO
	unset USE_GENTOO_VERSION
	# use Gentoo Python 3.7.7 even here, only for EasyBuild itself
	export EB_PYTHON=/cvmfs/soft.computecanada.ca/gentoo/2020/usr/bin/python
fi
EASYBUILD_CONFIG_ROOT=$EASYBUILD_ROOT/easybuild-computecanada-config/$YEAR
export LOCAL_EASYBUILD_CONFIGFILES=$EASYBUILD_ROOT/config.cfg,$EASYBUILD_CONFIG_ROOT/config.cfg
export EASYBUILD_SUBDIR_MODULES=modules/$YEAR
export EASYBUILD_SUBDIR_SOFTWARE=software/$YEAR
export EASYBUILD_SUBDIR_USER_MODULES=.local/easybuild/$EASYBUILD_SUBDIR_MODULES
export PATH=${PATH%%:/usr/bin}
export EASYBUILD_REPOSITORY='GitRepository'

# use associative arrays for arch-dependent EB settings
declare -A repositorypath robot_paths optarch

repositorypath[avx2]=$EASYBUILD_ROOT/ebfiles_repo.git,$YEAR
robot_paths[avx2]=$EASYBUILD_ROOT/ebfiles_repo/$YEAR
for rsnt_arch in sse3 avx avx512; do
	repositorypath[$rsnt_arch]=$EASYBUILD_ROOT/ebfiles_repo_$rsnt_arch.git,$YEAR
	robot_paths[$rsnt_arch]=$EASYBUILD_ROOT/ebfiles_repo_$rsnt_arch/$YEAR:${robot_paths[avx2]}
done

declare -A optarch
if [ "$YEAR" -ge 2023 ]; then
    optarch=(
	[avx2]='NVHPC:-march=x86-64-v3;Intel:-march=core-avx2 -axCore-AVX512;GCC:-march=x86-64-v3;LLVM:-march=x86-64-v3 -mtune=generic'
	[avx512]='NVHPC:-march=x86-64-v4;Intel:-march=skylake-avx512;GCC:-march=x86-64-v4;LLVM:-march=x86-64-v4 -mtune=znver5'
    )
elif [ "$YEAR" -ge 2020 ]; then
    optarch=(
	[avx2]='NVHPC:tp=haswell;Intel:march=core-avx2 -axCore-AVX512;GCC:march=core-avx2'
	[avx512]='NVHPC:tp=skylake;Intel:xCore-AVX512;GCC:march=skylake-avx512'
	[avx]='NVHPC:tp=sandybridge;Intel:xAVX;GCC:march=corei7-avx'
	[sse3]='NVHPC:tp=px;Intel:msse3;GCC:march=nocona -mtune=generic'
    )
else
    optarch=(
	[avx2]='PGI:tp=haswell;Intel:xCore-AVX2;GCC:march=core-avx2;GCCcore:GENERIC'
	[avx512]='PGI:tp=skylake;Intel:xCore-AVX512;GCC:march=skylake-avx512;GCCcore:GENERIC'
	[avx]='PGI:tp=sandybridge;Intel:xAVX;GCC:march=corei7-avx;GCCcore:GENERIC'
	[sse3]='PGI:tp=px;Intel:msse3;GCC:march=nocona -mtune=generic;GCCcore:GENERIC'
    )
fi

CURRENT_USER="$(whoami)"
if [ -n "$SUDO_USER" ] ; then
	ORIG_USER="$SUDO_USER"
else
	ORIG_USER="$CURRENT_USER"
fi
if [ "$CURRENT_USER" != "ebuser" ] ; then
	export EASYBUILD_PREFIX=$HOME/.local/easybuild
	export EASYBUILD_SUBDIR_USER_MODULES=''
        export EASYBUILD_REPOSITORY='FileRepository'
	repositorypath[avx2]=$EASYBUILD_PREFIX/ebfiles_repo,$YEAR
	robot_paths[avx2]=$EASYBUILD_PREFIX/ebfiles_repo/$YEAR:${robot_paths[avx2]}
	for rsnt_arch in sse3 avx avx512; do
	    repositorypath[$rsnt_arch]=$EASYBUILD_PREFIX/ebfiles_repo_$rsnt_arch,$YEAR
	    robot_paths[$rsnt_arch]=$EASYBUILD_PREFIX/ebfiles_repo_$rsnt_arch/$YEAR:$EASYBUILD_PREFIX/ebfiles_repo/$YEAR:${robot_paths[$rsnt_arch]}
	done
else
	if [[ "$ORIG_USER" != "ebuser" && ( -z "$GIT_AUTHOR_NAME" || $GIT_AUTHOR_NAME == "EasyBuild User" ) ]]; then
		echo "Failed to read \$HOME/.git_env_vars.sh. Please make sure they are readable and configured as described on https://wiki.computecanada.ca/staff/RSNT_Software_-_Setting_up#Configuring_your_build_node_account"
		exit 1
	fi
	if [ "$(id -ng)" != "ebuser" ] ; then
		# using ebuser with different group ID
		export EASYBUILD_INSTALLPATH_SOFTWARE=/cvmfs/restricted.computecanada.ca/easybuild/$EASYBUILD_SUBDIR_SOFTWARE
		export EASYBUILD_SOURCEPATH=/cvmfs/restricted.computecanada.ca/easybuild/sources
	fi
	cd /shared_tmp/logs # needed for --job
fi
if [ "$YEAR" -ge "2023" ]; then
	EB=$EBROOTGENTOO/bin/eb
else
	export PYTHONPATH=$EASYBUILD_ROOT/site-packages
	EB=$EASYBUILD_ROOT/framework/eb
fi
export EASYBUILD_JOB_EB_CMD="srun --mpi=none --ntasks=1 $EB"
export EASYBUILD_HOOKS=$EASYBUILD_CONFIG_ROOT/cc_hooks.py
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export RSNT_EASYBUILD_MAGIC_COOKIE=263ca73bb634185aab1d1b41627fdbba

# argument validation
NEW_ARGS=()
unset from_pr
unset job
unset arch
unset use_bwrap
for argument in "$@"; do
	if [[ $argument =~ ^--disable-enforce-checksums$ ]]; then
		# workaround for non-propagation of this argument
		export EASYBUILD_JOB_EB_CMD="$EASYBUILD_JOB_EB_CMD $argument"
	fi
	if [[ $argument =~ ^--job-cores=[0-9]*$ ]]; then
		kv=(${argument//=/ })
		echo "Job-cores specified to ${kv[1]}, setting EASYBUILD_PARALLEL=${kv[1]}"
		export EASYBUILD_PARALLEL=${kv[1]}
	fi
	if [[ $argument =~ ^--(include-easyblocks-|)from-pr($|=) ]]; then
		from_pr=1
	fi
	if [[ $argument =~ ^--job$ ]]; then
		# so we can follow the job output with e.g. tail -f
		export PYTHONUNBUFFERED=1
		echo "Output of job will be in $PWD/%x-%j.out"
		job=1
	fi
	if [[ $argument =~ .*.eb$ ]]; then
		ec="$argument"
	fi
	if [[ $argument =~ ^--bwrap$ ]]; then
		use_bwrap=1
	elif [[ $argument =~ ^--arch=.*$ ]]; then
		kv=(${argument//=/ })
		arch=${kv[1]}
	elif [[ "$CURRENT_USER" == "ebuser" ]]; then
		if [[ $argument =~ --inject-checksums* || $argument =~ --robot* || "$argument" == "-r" ]]; then
			echo "Please do not use $argument as $CURRENT_USER"
			exit 1
		fi
		if [[ $argument =~ ^--installpath-software=/cvmfs/data.rsnt.computecanada.ca/.* ]]; then
			if [[ "$argument" != "--installpath-software=/cvmfs/data.rsnt.computecanada.ca/content/easybuild/data/2020" ]]; then
				echo "When installing datasets, the install path should be /cvmfs/data.rsnt.computecanada.ca/content/easybuild/data/2020 instead of $argument"
				exit 1
			fi
		fi
		if [[ $argument =~ .*.eb$ ]]; then
			if [[ $argument =~ ^/cvmfs/soft.computecanada.ca/easybuild/software/.* ]]; then
				NEW_ARGS+=("$argument")
				# accept this path, it is used by the auto recompilation
				continue 
			elif [[ $argument =~ .*/.* ]]; then
				echo "Please do not use a path to specify the easyconfig."
				echo "Error on argument: $argument"
				exit 1
			else
				# We want to prevent eb from using $EASYBUILD_ROOT/easyconfigs for
				# dependencies so this is not in the robot path. To find the
				# main easyconfig there we switch to its directory.
				letter=${argument::1}
				letter=${letter,} # lowercase first letter
				name=${argument%%-*}
				# some names contain - (e.g. HOOMD-blue) so we need pathname expansion
				custom_ec=$(find $EASYBUILD_ROOT/site-packages/custom-easyconfigs/easybuild/easyconfigs/$letter/$name* -name $argument 2>/dev/null || true)
				if [[ -n "$custom_ec" && -f "$custom_ec" ]]; then
					# custom easyconfigs have priority
					ec="$custom_ec"
				else
					ec=$(find $EASYBUILD_ROOT/easyconfigs/$letter/$name* -name $argument 2>/dev/null)
					if [[ -z "$ec" || ! -f "$ec" ]]; then
						echo "Easyconfig $argument not found"
						exit 1
					fi
				fi
				NEW_ARGS+=("$ec")
			fi
		else
			NEW_ARGS+=("$argument")
		fi
	else
		NEW_ARGS+=("$argument")
	fi
done

if [[ $HOSTNAME =~ archimedes.c3.ca$ && -n "$job" && -n "$from_pr" ]]; then
	# Needed for --from-pr --job so
	# on-the-fly easyconfigs are passed to the job from shared_tmp.
	# Setting TMPDIR (unlike EASYBUILD_TMPDIR) here the job itself
	# (unlike the submitter) will use a private TMPDIR
	export TMPDIR="/shared_tmp"
	export EASYBUILD_DISABLE_CLEANUP_TMPDIR=1
fi

if [[ -n "$SLURM_CPUS_ON_NODE" ]]; then
	export EASYBUILD_PARALLEL=$SLURM_CPUS_ON_NODE
fi

if [[ "$CURRENT_USER" == "ebuser" && -z "$arch" ]]; then
	arch="avx2,avx512"
fi

if [[ -n "$arch" ]]; then
	if [[ ! -f "$ec" ]]; then
		echo "Easyconfig file "$ec" not found."
		echo "Please specify an explicit easyconfig when using --arch"
		exit 1
	fi
python <<EOF || arch=avx2
import sys
from easybuild.framework.easyconfig.parser import EasyConfigParser
ecp = EasyConfigParser("$ec")
name = ecp.get_config_dict()['toolchain']['name']
sys.exit(name == 'system' or name == 'dummy')
EOF
	echo "Building for arch=$arch"
else
	arch=$RSNT_ARCH
fi

custom_robot_path=$EASYBUILD_ROOT/site-packages/custom-easyconfigs/easybuild/easyconfigs
orig_buildpath=$EASYBUILD_BUILDPATH
for rsnt_arch in $(IFS=","; echo $arch); do
	export EASYBUILD_REPOSITORYPATH=${repositorypath[$rsnt_arch]}
	export EASYBUILD_ROBOT_PATHS=$custom_robot_path:${robot_paths[$rsnt_arch]}:
	export EASYBUILD_OPTARCH=${optarch[$rsnt_arch]}
	unset EASYBUILD_USE_CCACHE
	if [[ $HOSTNAME =~ archimedes.c3.ca$ && "$rsnt_arch" == "avx2" ]]; then
		EASYBUILD_USE_CCACHE=/tmp/ccache
		if [ ! -d $EASYBUILD_USE_CCACHE ]; then
			# create multiuser ccache
			mkdir -p $EASYBUILD_USE_CCACHE
			chgrp rsnt_soft $EASYBUILD_USE_CCACHE
			chmod g+s $EASYBUILD_USE_CCACHE
			setfacl -m "d:o:rx" $EASYBUILD_USE_CCACHE
		fi
		export CCACHE_BASEDIR=/tmp/$USER
	fi
	export RSNT_ARCH=$rsnt_arch
	module --force purge
	export MODULEPATH=/cvmfs/soft.computecanada.ca/custom/modules-$RSNT_ARCH
	if [ -z "$USE_NIX" ]; then
		module load gentoo/$YEAR
	else
		module load nixpkgs/16.09
	fi
	export EASYBUILD_BUILDPATH=$orig_buildpath/$rsnt_arch
	export MODULEPATH=$EASYBUILD_ROOT/$EASYBUILD_SUBDIR_MODULES:$MODULEPATH
	if [ -n "use_bwrap" ]; then
		bwrapdir=$(mktemp -d -p /bwrap)
		echo "Building via bwrap in $bwrapdir"
		EASYBUILD_CONFIG_ROOT=$HOME/easybuild-computecanada-config/2023
		bwrapcmd=$(RSNT_ARCH="$rsnt_arch" python $EASYBUILD_CONFIG_ROOT/../bwrapcmd.py $ec $bwrapdir)
		$bwrapcmd $EB --configfiles=$LOCAL_EASYBUILD_CONFIGFILES "${NEW_ARGS[@]}" --ignore-locks
	else
		$EB --configfiles=$LOCAL_EASYBUILD_CONFIGFILES "${NEW_ARGS[@]}"
	fi
done
